# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

version: "3.9"
services:
  local_network:
    image: local-network-image
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: local_network_test
    init: true
    working_dir: /code
    entrypoint: [ "/code/docker/run_setup.sh" ]
    network_mode: "host"
    volumes:
      - type: bind
        source: ./
        target: /code/
  relayer:
    image: awm-relayer:<TAG>
    container_name: relayer_test
    init: true
    working_dir: /code
    entrypoint: /code/docker/run_relayer.sh
    network_mode: "host"
    user: "root"
    volumes:
      - type: bind
        source: ./
        target: /code/
  test_runner:
    image: test-runner-image
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: test_runner
    init: true
    working_dir: /code
    entrypoint: /code/docker/run_tests.sh
    network_mode: "host"
    volumes:
      - type: bind
        source: ./
        target: /code/
    environment:
      - TEST_TARGET=${TEST_TARGET}
