# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

version: "3.9"
services:
  local_network:
    image: local-network-image
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        ARCH: ${ARCH} # set by run.sh
        GO_VERSION: ${GO_VERSION} # set by run.sh
    container_name: local_network_run
    init: true
    working_dir: /code
    entrypoint: ["/code/docker/run_setup.sh"]
    network_mode: "host"
    volumes:
      - type: bind
        source: ./
        target: /code/
  relayer:
    image: avaplatform/awm-relayer:v0.2.9
    container_name: relayer_run
    init: true
    working_dir: /code
    entrypoint: /code/docker/run_relayer.sh
    network_mode: "host"
    user: "root"
    volumes:
      - type: bind
        source: ./
        target: /code/
