# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: "1.20.7"

jobs:
  e2e_tests:
    name: e2e_tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install AvalancheGo Release
        run: |
          cd subnet-evm
          BASEDIR=/tmp/e2e-test AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego ./scripts/install_avalanchego_release.sh

      - name: Build Subnet-EVM Plugin Binary
        run: |
          cd subnet-evm
          ./scripts/build.sh /tmp/e2e-test/avalanchego/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy

      - name: Checkout teleporter repository
        uses: actions/checkout@v4

      - name: Install Forge
        # Forge installs to BASE_DIR, but updates the PATH definition in $HOME/.bashrc
        run: |
          BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          $BASE_DIR/.foundry/bin/foundryup

      - name: Run E2E Tests
        run: AVALANCHEGO_BUILD_PATH=/tmp/e2e-test/avalanchego DATA_DIR=/tmp/e2e-test/data ./scripts/local/e2e_test.sh
